import { Router } from 'express';
import { overviewRouter } from './overview';
import { parentsRouter } from './parents';
import { studentsRouter } from './students';
import { tutorsRouter } from './tutors';
import { classesRouter } from './classes';
import { lessonsRouter } from './lessons';
import { attendanceRouter } from './attendance';
import { studentPaymentsRouter, tutorPaymentsRouter } from './payments';
import { progressReportsRouter } from './progress-reports';
import { homeworkRouter } from './homework';
import { announcementsRouter } from './announcements';
import { resourcesRouter } from './resources';
import { auditRouter } from './audit';
import { alertsRouter } from './alerts';
import { botJobsRouter } from './bot-jobs';
import { botHealthRouter } from './bot-health';
import { calendarRouter } from './calendar';

export const adminRouter = Router();

adminRouter.use('/', overviewRouter);
adminRouter.use('/parents', parentsRouter);
adminRouter.use('/students', studentsRouter);
adminRouter.use('/tutors', tutorsRouter);
adminRouter.use('/classes', classesRouter);
adminRouter.use('/lessons', lessonsRouter);
adminRouter.use('/attendance', attendanceRouter);
adminRouter.use('/', studentPaymentsRouter);
adminRouter.use('/', tutorPaymentsRouter);
adminRouter.use('/progress-reports', progressReportsRouter);
adminRouter.use('/homework', homeworkRouter);
adminRouter.use('/announcements', announcementsRouter);
adminRouter.use('/resources', resourcesRouter);
adminRouter.use('/', auditRouter);
adminRouter.use('/', alertsRouter);
adminRouter.use('/bot-jobs', botJobsRouter);
adminRouter.use('/bot-health', botHealthRouter);
adminRouter.use('/calendar', calendarRouter);
